# Generated by Django 2.2.6 on 2019-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191022_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='user_image/beach.jpg', null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='user_image/default.jpg', null=True, upload_to='user_image/'),
        ),
    ]
