# Generated by Django 2.2.6 on 2019-10-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191022_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/beach_pollution.jpg', null=True, upload_to='media'),
        ),
    ]
